# Generated by Django 4.2.10 on 2024-02-23 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_businesstype_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.services')),
            ],
        ),
    ]
